on:
  workflow_call:
    inputs:
      msg:
        required: false
        type: string
        default: 'Gopi'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: mulple line commands
        run: |
          echo ${{ inputs.msg }}
          ls -la
          env
        working-directory: .
