on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: mulple line commands
        run: |
          echo "Hello world"
          ls -la
          env
        working-directory: .
