on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        default: .



jobs:
  init_workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - run: terraform --version

    - run: terraform init
      working-directory: ${{ inputs.working_dir }}
