# name: 'Terraform Apply'

# on:
#   workflow_call:

# jobs:
#   terraform-apply:
#     name: 'Terraform Apply'

#     runs-on: ubuntu-latest

#     steps:

#       - name: Terraform Apply

#         uses: hashicorp/terraform-github-actions@master
#         with:
#           tf_actions_version: 0.14.8
#           tf_actions_subcommand: 'apply'

