on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        default: .

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_NAME: "Gopi GH Actions"


jobs:
  init_workflow:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: get-tf-version
      run: |
        terraform --version
        ls -la
        env | grep ARM

    - run: terraform init
      working-directory: ${{ inputs.working_dir }}
