# name: 'Terraform niti'

# on:
#   workflow_call:

# jobs:

#   terraform-init:
#     name: 'Terraform Validate'

#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         shell: bash

#     steps:

#       - name: 'Terraform Validate'
#         uses: hashicorp/terraform-github-actions@master
#         with:
#          tf_actions_version: 0.14.8
#          tf_actions_subcommand: 'validate'

