name: AZ_login
on:
  workflow_call:

jobs:
  azlogin:
    runs-on: ubuntu-latest
    steps:


      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
           creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
